profile:
  name: prod

server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://sbt_mysql:3306/mydb?serverTimezone=UTC&max_allowed_packet=15728640
    username: root
    password: admin

    driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    ## 让404错误抛出异常，需要同时设置spring.resources.add-mappings为false
    #  让404错误抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false #禁用静态资源的自动映射，如不禁用，不存在的url将被映射到/**，servlet不有机会抛出异常
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1
    port: 6379
    password: "" # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

# logging:
#   level:
#     root: DEBUG

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kuka.springtemplate.model
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: my_secret_2021
  expiration: 1800