name: 'spring boot template'

version: 1.0.0.0

server:  
  port: 8090  
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8  

spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
  mvc:
    ## 让404错误抛出异常，需要同时设置spring.resources.add-mappings为false
    #  让404错误抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false #禁用静态资源的自动映射，如不禁用，不存在的url将被映射到/**，servlet不有机会抛出异常

# logging:
#   level:
#     root: DEBUG

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kuka.CSServer.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: my_secret_2021
  expiration: 1800